;=============================
; Billion Parser
; Author: Voipcenter
;=============================

exten => 50,1,Answer()
 same => n,Set(var1=23546987912)
 same => n,GotoIf($[${LEN(${var1})}<10]?say)
 same => n,Set(FL=$[${LEN(${var1})}-9])
 same => n,NoOp(${FL})
 same => n,SayNumber(${var1:0:${FL}})
 same => n,Playback(pr/digits/billion-o)
 same => n,SayNumber(${var1:-9})
 same => n,Hangup()

exten => 50,n(say),SayNumber(${var1})
 same => n,Hangup()
